# Generated by Django 3.0.5 on 2021-03-02 09:34

from django.db import migrations, models
import employee.validation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='last Name')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('phone_no', models.CharField(max_length=16, validators=[employee.validation.Phone_number_validator], verbose_name='phoneno')),
                ('email', models.CharField(max_length=25, unique=True, validators=[employee.validation.Email_validator], verbose_name='Email')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
    ]
